### ISSUE TITLE
DB TODO List

### ISSUE THREAD

**Issue by dmHyeon** [baDream/AwesomeMusic#1]
1. 삽입 문제
유저디비가 없을때 - 걍삽입
유저디비가 있을때
미디어디비와 패쓰로 대조
미디어디비 패쓰와 같을때
미디어디비 패쓰와 다를때
각각 두가지 경우
 - 유저디비에 미디어디비 패쓰로 대조
 - 유저디비에있고 미디어디비에없는경우 삭제된자료 

2. 백그라운드 서비스 구현
3. 파일명을 이용한 메타데이터 매칭

**Comment by greatsk55** [comment]
유저디비가 없을때 - clear
파일명을 이용한 메타데이터 매칭 - clear

**Comment by greatsk55** [comment]
문제가 많아서 갈아 엎기로 함
